import 'package:flutter/material.dart';

var server = "https://light-maps-melt-49-145-232-7.loca.lt";

List<DateTime> getDateList(DateTime date) {
  return [
    date.subtract(Duration(days: 30)),
    date.subtract(Duration(days: 29)),
    date.subtract(Duration(days: 28)),
    date.subtract(Duration(days: 27)),
    date.subtract(Duration(days: 26)),
    date.subtract(Duration(days: 25)),
    date.subtract(Duration(days: 24)),
    date.subtract(Duration(days: 23)),
    date.subtract(Duration(days: 22)),
    date.subtract(Duration(days: 21)),
    date.subtract(Duration(days: 20)),
    date.subtract(Duration(days: 19)),
    date.subtract(Duration(days: 18)),
    date.subtract(Duration(days: 17)),
    date.subtract(Duration(days: 16)),
    date.subtract(Duration(days: 15)),
    date.subtract(Duration(days: 14)),
    date.subtract(Duration(days: 13)),
    date.subtract(Duration(days: 12)),
    date.subtract(Duration(days: 11)),
    date.subtract(Duration(days: 10)),
    date.subtract(Duration(days: 9)),
    date.subtract(Duration(days: 8)),
    date.subtract(Duration(days: 7)),
    date.subtract(Duration(days: 6)),
    date.subtract(Duration(days: 5)),
    date.subtract(Duration(days: 4)),
    date.subtract(Duration(days: 3)),
    date.subtract(Duration(days: 2)),
    date.subtract(Duration(days: 1)),
    date,
    // date.add(Duration(days: 1)),
    // date.add(Duration(days: 2)),
    // date.add(Duration(days: 3)),
    // date.add(Duration(days: 4)),
    // date.add(Duration(days: 5)),
    // date.add(Duration(days: 6)),
    // date.add(Duration(days: 7)),
    // date.add(Duration(days: 8)),
    // date.add(Duration(days: 9)),
    // date.add(Duration(days: 10)),
    // date.add(Duration(days: 11)),
    // date.add(Duration(days: 12)),
    // date.add(Duration(days: 13)),
    // date.add(Duration(days: 14)),
    // date.add(Duration(days: 15)),
    // date.add(Duration(days: 16)),
    // date.add(Duration(days: 17)),
    // date.add(Duration(days: 18)),
    // date.add(Duration(days: 19)),
    // date.add(Duration(days: 20)),
    // date.add(Duration(days: 21)),
    // date.add(Duration(days: 22)),
    // date.add(Duration(days: 23)),
    // date.add(Duration(days: 24)),
    // date.add(Duration(days: 25)),
    // date.add(Duration(days: 26)),
    // date.add(Duration(days: 27)),
    // date.add(Duration(days: 28)),
    // date.add(Duration(days: 29)),
    // date.add(Duration(days: 30))
  ];
}

List<MaterialAccentColor> colorList = [
  Colors.redAccent,
  Colors.blueAccent,
  Colors.greenAccent,
  Colors.purpleAccent,
  Colors.orangeAccent,
];
